name: release-please

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      sha: ${{ steps.release.outputs.sha }}
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    uses: ./.github/workflows/release.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      tag: ${{ needs.release-please.outputs.tag }}
      version: ${{ needs.release-please.outputs.version }}
      major: ${{ needs.release-please.outputs.major }}
      minor: ${{ needs.release-please.outputs.minor }}
      sha: ${{ needs.release-please.outputs.sha }}
